### PR TITLE
Add support for scala 2.13.0-M5

### PR DESCRIPTION
**Pull request by raboof**
Refs #27

### CODE REVIEW

**Comment by dwijnand** [comment]
I think https://github.com/playframework/play-file-watch/pull/25 and https://github.com/playframework/play-file-watch/pull/26 helped here 😄

**Comment by raboof** [comment]
Ah indeed I was surprised it was so smooth :smile: - thanks!

**Comment by dwijnand** [comment]
I'm surprised by that last diff (toList).

**Comment by dwijnand** [comment]
My point is why wasn't it failing the community build (which is what drop to #25 and #26.)

Also, just so you know, it's not `scala.collection.Seq` that changed but `scala.Seq`: https://github.com/scala/scala/blob/v2.13.0-M5/src/library/scala/package.scala#L52-L54

`scala.collection.Seq` remains as the "we don't know"-mutability `Seq`, and importing that is a 3rd option I've seen (and used.)

**Comment by raboof** [comment]
Good one on `scala.Seq` vs `scala.collection.Seq`, indeed this was about `scala.Seq`.

Not sure about the community build, I don't see play-file-watch in https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1723/consoleText at all

**Comment by dwijnand** [comment]
Hmm, that's probably because play's sbt plugin should be excluded, but then what triggered #25 and #26?? 🔄🔄🔁🔁🔃🔃  Maybe it's clearer to @SethTisue.

**Comment by SethTisue** [comment]
> I don't see play-file-watch in https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1723/consoleText 

adding play-file-watch to the community build is part of https://github.com/scala/community-builds/pull/819, which we're still working on

**Comment by raboof** [comment]
AppVeyor error:
```
Exception in thread "specs2-1" java.lang.UnsatisfiedLinkError: C:\projects\play-file-watch\target\jnotify\jnotify\native_libraries\64bits\jnotify_64bit.dll: The process cannot access the file because it is being used by another process
```

Not sure if that's related to this PR?

**Comment by marcospereira** [comment]
> Not sure if that's related to this PR?

Yeah, I don't think it is related to the PR. Let me close/reopen to trigger a new build.

**Comment by dwijnand** [comment]
see https://github.com/playframework/play-file-watch/issues/27#issuecomment-465445997

**Pull request closed without merging**
