### PR TITLE
Replace Scala 2.10 support with Scala 2.12 support

### PR DESCRIPTION
**Pull request by benmccann**
I'd love a new release after this is merged

### CODE REVIEW

**Comment by wsargent** [comment]
@benmccann I don't know that @jroper didn't intend for this to be used in an sbt context, so 2.10 support may be significant here.

**Comment by benmccann** [comment]
This is [used by](https://github.com/lagom/lagom/blob/master/project/Dependencies.scala#L277) Lagom's [build-tool-support](https://github.com/lagom/lagom/blob/master/build.sbt#L835). Lagom master currently only supports Scala 2.11, so I believe we shouldn't need to keep Scala 2.10 support

It wouldn't be easy to support both Scala 2.10 and Scala 2.12 at the same time because there's no version of the betterfiles dependency which is published for both simultaneously.

I'm curious why you say this shouldn't be used in an sbt context as Lagom's sbt-plugin uses this.

Aren't these files just copy-pasted from Play? I was planning to send a PR to have Play use this repo to cut down on code duplication

**Comment by wsargent** [comment]
This is copied from Play -- I said I don't know that it wasn't intended to be used in an sbt context.  If it is for sbt, then it should be 2.10 because sbt is 2.10.

**Comment by benmccann** [comment]
Thanks for clarifying. I didn't read your original comment correctly

 In Play it's used by the [run-support project](http://search.maven.org/#search%7Cga%7C1%7Crun-support), which doesn't use 2.10.

But in Lagom it's used by the [build-tool-support project](http://search.maven.org/#search%7Cga%7C1%7Cbuild-tool-support) and on second look it looks like that actually might depend on 2.10.

**Pull request closed without merging**
