### PR TITLE
WIP - Scala 2.12 upgrade

### PR DESCRIPTION
**Pull request by wsargent**
WORK IN PROGRESS DO NOT MERGE

### CODE REVIEW

**Comment by benmccann** [comment]
I don't think there's any version of betterfiles published for both 2.10 and 2.12

Also, we should setup Travis for this project

**Comment by benmccann** [comment]
@gmethvin suggested this isn't needed in https://github.com/playframework/playframework/pull/7076#issuecomment-291948828

**Comment by gmethvin** [comment]
It would still be useful to have this for other potential usages, and for Play in the future when SBT switches off 2.10.

**Comment by gmethvin** [comment]
If we're using this to implement the run mode for maven or some other build system, I don't see a reason not to use the latest scala version.

**Comment by benmccann** [comment]
You'd have to remove the betterfiles dependency to make it build for both Scala 2.10 and Scala 2.12 because there's no version of betterfiles published for both of those Scala versions. I wouldn't be opposed to that change, but I'm also not quite sure it's worth it.

**Comment by gmethvin** [comment]
For better-files, it should be safe to use 2.17.0 for scala 2.10 and 2.17.1 for 2.11/2.12. There were no API changes between the two. See https://oss.sonatype.org/content/repositories/releases/com/github/pathikrit/

**Comment by benmccann** [comment]
Good point. I hadn't really thought about using different version of betterfiles for different versions of Scala. I'm just so used to having a single version and using the `%%` syntax that I didn't really think about anything being possible.

Okay, this all makes sense. Ignore my previous comments :-)

**Pull request closed without merging**
