### PR TITLE
Remove JNotify

### LINKED ISSUE #46: Tests fail on JDK 12
This turned up in the Scala 2.12 community build, running on JDK 12.

It's also easily reproducible outside dbuild, just fire up sbt and run `test`. The result is:

```
[info] JNotifyFileWatchServiceSpec
[info] 
[info] The file watch service should
[error]   ! detect new files
[error]    java.lang.NoSuchFieldException: sys_paths (JNotifyFileWatchService.scala:102)
[error] play.dev.filewatch.JNotifyFileWatchService$.$anonfun$apply$2(JNotifyFileWatchService.scala:102)
[error] play.dev.filewatch.JNotifyFileWatchService$.$anonfun$apply$1(JNotifyFileWatchService.scala:75)
[error] play.dev.filewatch.JNotifyFileWatchService$.apply(JNotifyFileWatchService.scala:73)
[error] play.dev.filewatch.FileWatchService$.jnotify(FileWatchService.scala:92)
[error] play.dev.filewatch.JNotifyFileWatchServiceSpec.watchService(FileWatchServiceSpec.scala:25)
[error] play.dev.filewatch.FileWatchServiceSpec.watchFiles(FileWatchServiceSpec.scala:85)
[error] play.dev.filewatch.FileWatchServiceSpec.$anonfun$new$5(FileWatchServiceSpec.scala:97)
[error] play.dev.filewatch.FileWatchServiceSpec.withTempDir(FileWatchServiceSpec.scala:51)
[error] play.dev.filewatch.FileWatchServiceSpec.$anonfun$new$4(FileWatchServiceSpec.scala:96)
```

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #46

JNotify is outdated, not maintained, not necessary and it doesn't work well with upcoming JDKs.

### CODE REVIEW

**Review by marcospereira — APPROVED** [review]

**Comment by mkurz** [comment]
@marcospereira I think we should make a `1.1.x` branch based off current `master` so we don't add this change to the next release version 1.1.15.... IMHO removing JNotifyFileWatchService should go into a 1.2.0 release.
However actually there is `1.1.x` branch already, but it is not relevant anymore - that's because after the 1.1.12 release from that 1.1.x branch the next release 1.1.13 was done from master branch by releasing it by tag.
I think we can just either remove the current 1.1.x branch and create a new one from current HEAD or force push the current 1.1.x branch... However I don't have to permission to do so (1.1.x is protected). Could you do that instead? Thanks!

**Comment by marcospereira** [comment]
@mkurz done! :-)

**Comment by mkurz** [comment]
Thanks!

**Comment by mkurz** [comment]
https://github.com/playframework/jnotify is now archived as well.

**Pull request merged**
